Feature - Warehouses tests
LucasTI79/meli_bootcamp_go_w2-2 pull request #25
Opened 2023-06-26 14:16 UTC by brenda-mercadolivre

### O que foi realizado?
Foram implementados testes unitários para os endpoints de Warehouse.

**PR relacionado:**
Não se aplica.

**Link do Trello:**

2023-06-26 20:59 UTC, maicodsantos approved these changes

2023-06-26 21:09 UTC, maicodsantos approved these changes

2023-06-27 13:04 UTC, vinicius-junior requested changes

2023-06-27 13:04 UTC, vinicius-junior commented on internal/warehouse/service.go
> +	GetOne(c *context.Context, d int) (*domain.Warehouse, error)
Voltar o nome pra id.

2023-06-27 13:04 UTC, vinicius-junior commented on internal/warehouse/service_test.go
> +		warehouseRepositoryMock.On("GetAll", ctx).Return([]domain.Warehouse{}, errors.New("error"))
Usar o assert.AnError para representar um erro genérico.

2023-06-27 13:04 UTC, vinicius-junior commented on internal/warehouse/service_test.go
> +		assert.Error(t, err)
Nesses casos onde está especificando um erro personalizado, pode checar com o assert.Equal para ver se o erro é do tipo que está esperando.

2023-06-27 14:22 UTC, vinicius-junior approved these changes

2023-06-27 14:48 UTC, dudameregali reviewed
ok

2023-06-27 15:22 UTC, merged